### ISSUE TITLE
error while calling signin method on android

### ISSUE THREAD

**Issue by xurazCaseey** [CodetrixStudio/CapacitorGoogleAuth#168]
here is my log;

Capacitor/Plugin: Something went wrong
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@18.1.0:9)
        at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.signInResult(GoogleAuth.java:73)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:155)
        at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0$Plugin(Plugin.java:117)
        at com.getcapacitor.-$$Lambda$Plugin$9tit0PZrRMA5UA4Z_xqI4yDk4JY.onActivityResult(Unknown Source:6)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:362)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:322)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:634)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:216)
        at android.app.Activity.dispatchActivityResult(Activity.java:7599)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by kaimallie** [comment]
Got the same issue, but found a solution! [Read](https://github.com/googlesamples/google-services/issues/360#issuecomment-381648685) that error 10 mostly is solved by adding the SHA1 key. 

1. So first I added the SHA1 key from Google Play Console (see Setup > Integrity page) to Google Cloud API Client ID + Firebase Android.
2. Next you need to check [these steps](https://developers.google.com/identity/sign-in/android/start) to add your computer SHA1 to Google APIs. Maybe it's already there, you need to verify first. 
3. Then I searched for server_client_id in my Android Studio app and replaced all values by my auto-generated 'Web application' client ID value in Google APIs. Apparently I got the wrong client id over there. Also I re-imported the google-services.json file after all these steps from Firebase to be sure. 

Works now again :-)

**Comment by xurazCaseey** [comment]
thanks !! works for me also after changing the client Id of type Web application.
