### ISSUE TITLE
Android app crashes on launch

### ISSUE THREAD

**Issue by OnlinePage** [CodetrixStudio/CapacitorGoogleAuth#294]
Hi I am trying to use latest version `3.3.2` with  `npm i --save @codetrix-studio/capacitor-google-auth` and then 

`npx cap update`

when app is now build with `ionic cap sync` and launched on device via android studio: IT CRASHES!! 😲  and doestn launch.
Can't even see debug log when launched with debugger attached😔.

What could posssible go wrong🤔?

I am using capacitor 5 
`"
    "@capacitor/android": "5.2.1",
    "@capacitor/app": "^5.0.6",
    "@capacitor/browser": "^5.0.6",
    "@capacitor/clipboard": "^5.0.6",
    "@capacitor/core": "^5.2.1",
`

Okay when debugging I found below error trace:

`
Caused by: java.lang.NegativeArraySizeException: -1
                                                                                                    	at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.load(GoogleAuth.java:71)
                                                                                                    	at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
                                                                                                    	at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)

`

**Comment by Martin-Eckleben** [comment]
> Alright the issue was the options were not properly set in the `capacitor.config.js` But still now everytime login response is `error code 10` Please respond it , it totall urgent!!

How did you set them properly?
I'm there now as well.

Mine:
```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: <id>,
  appName: <name>,
  webDir: 'www',
  bundledWebRuntime: false,

  plugins: {
    GoogleAuth: {
      clientId: '<clientID>.apps.googleusercontent.com'
    },
  },
}

export default config
```

**Comment by Martin-Eckleben** [comment]
I solved it with

```
  plugins: {

    GoogleAuth: {
      scopes: ["profile", "email"],
      clientId: '<clientID>.apps.googleusercontent.com',
    },
  },
```

Then I did not even have to state it in the initialize call anymore (as it was described in the Readme.md):
`GoogleAuth.initialize();`
