### ISSUE TITLE
Prevent error from being thrown if not using plugin for web

### ISSUE THREAD

**Issue by kyleabens** [CodetrixStudio/CapacitorGoogleAuth#33]
I'm currently implementing this plugin for iOS and Android only and noticed that if I don't include the client ID meta tag I get the following error in the browser:

```
zone.js:703 Unhandled Promise rejection: Cannot read property 'content' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'content' of undefined
    at HTMLScriptElement.<anonymous> (web.js:33)
    at Generator.next (<anonymous>)
    at web.js:6
    at new ZoneAwarePromise (zone.js:931)
    at push../node_modules/@codetrix-studio/capacitor-google-auth/dist/esm/web.js.__awaiter (web.js:2)
    at web.js:31
    at platform.js:23
    at jb (platform.js:15)
    at ea (platform.js:23)
    at Array.Qb.F.<computed> (platform.js:23) TypeError: Cannot read property 'content' of undefined
    at HTMLScriptElement.<anonymous> (http://localhost:8100/vendor.js:94921:84)
    at Generator.next (<anonymous>)
    at http://localhost:8100/vendor.js:94894:71
    at new ZoneAwarePromise (http://localhost:8100/polyfills.js:3936:29)
    at push../node_modules/@codetrix-studio/capacitor-google-auth/dist/esm/web.js.__awaiter (http://localhost:8100/vendor.js:94890:12)
    at http://localhost:8100/vendor.js:94919:34
    at https://apis.google.com/js/platform.js:23:215
    at jb (https://apis.google.com/js/platform.js:15:467)
    at ea (https://apis.google.com/js/platform.js:23:198)
    at Array.Qb.F.<computed> (https://apis.google.com/js/platform.js:23:301)
```

I'm hoping there is an easy way to remove this error without adding the meta tag.  Thanks!

**Comment by Justas-S** [comment]
The quick and dirty way is to add a `meta` tag, but it will still load the web js script. You could try not importing this library at all, or if that fails only importing the definitions.

**Comment by kyleabens** [comment]
@Justas-S so by not importing the library do you mean not including `import "@codetrix-studio/capacitor-google-auth";` ?

**Comment by kyleabens** [comment]
Alright that did the trick and decreased my bundle size as well.  Thanks for the help!

**Comment by parveenkhtkr** [comment]
@kyleabens @Justas-S v1.4.1 solves it.
