### ISSUE TITLE
Plugin is not loaded in Android + Capacitor 6

### ISSUE THREAD

**Issue by scamps86** [CodetrixStudio/CapacitorGoogleAuth#362]
Hi there,

I wanted to share that I've updated to Capacitor 6 with version 3.4.0-rc.3. 
Everything works perfectly on iOS, but when trying on Android, I encounter the following error. 
I've followed all the migration guide steps from Capacitor 5 to 6 carefully and synced Gradle, but this issue persists. Any suggestions or hints on how to fix it? 

`
Registering plugin instance: GoogleAuth
NativePlugin com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth failed to load
com.getcapacitor.PluginLoadException: Unable to load plugin instance. Ensure plugin is publicly accessible
                                                                                                    	at com.getcapacitor.PluginHandle.load(PluginHandle.java:107)
                                                                                                    	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
                                                                                                    	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:680)
                                                                                                    	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:636)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Bridge.java:221)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1555)
                                                                                                    	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:48)
                                                                                                    	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:42)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-05-03 12:16:57.639 10064-10064 Capacitor/Console 
`

When I try to SignIn with Google, i get the following error:

`Google Sign in service:  login error Error: "GoogleAuth" plugin is not implemented on android`

Thanks in advance for any help you can provide!

**Comment by scamps86** [comment]
I've identified the error now. Essentially, I was defining the scopes while calling GoogleAuth.init() instead of **placing them in the Capacitor configuration.**

Upon inspecting GoogleAuth.java, I noticed it was attempting to access a negative index of the array because it couldn't detect any scopes in the array.

`Scope[] scopes = new Scope[scopeArray.length - 1];`

Maybe it should be useful to specify that "scope" in Capacitor's config is mandatory in the documentation.
