### ISSUE TITLE
Android Error on Google Sign In

### ISSUE THREAD

**Issue by lesjaw** [CodetrixStudio/CapacitorGoogleAuth#51]
here is the logcat said:

```
2020-05-16 22:42:54.137 1950-1950/com.lesjaw.astropasaraya E/Capacitor/Plugin: Something went wrong
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@18.0.0:9)
        at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.handleOnActivityResult(GoogleAuth.java:71)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:765)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:211)
        at android.app.Activity.dispatchActivityResult(Activity.java:7454)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-05-16 22:42:54.138 1950-1950/com.lesjaw.astropasaraya D/Capacitor: Sending plugin error: {"save":false,"callbackId":"115071079","pluginId":"GoogleAuth","methodName":"signIn","success":false,"error":{"message":"Something went wrong"}}
2020-05-16 22:42:54.145 1950-1950/com.lesjaw.astropasaraya D/Capacitor/App: Firing change: true
2020-05-16 22:42:54.146 1950-1950/com.lesjaw.astropasaraya D/Capacitor/App: No listeners found for event appStateChange
2020-05-16 22:42:54.166 1950-1950/com.lesjaw.astropasaraya D/Capacitor: App resumed
```

**Comment by lesjaw** [comment]
I think I have found the problem.. It was Client_ID credential, on how I created.. since I have create a webb app so in google developer console I create OAuth Client ID with application type is Web Application..

For this Client ID everything work as expected in browser, but if built the angular with capacitor for android then the error come up, since its not a Web Application but it is Android application..

So I create new OAuth ID but this time I choose android app, then I generate the SHA1 key with Android studio, and add my android app package name with this new  OAuth ID.. now with android app the google sign in is working fine.. but not with the web app in browser since the Client ID is now not registered for any http:// but only for android package name..

so to fix this  we need to put OAuth Client ID for the browser in app .module.ts like this:
```
const config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider('idforwebapp-xxxxxx.apps.googleusercontent.com')
  }

]);
```
and Client ID for the android (the one with application type android) we put in res/value/string

  `  <string name="server_client_id">idforAndroid-xxxxxxx.apps.googleusercontent.com</string>
`

thats it..

**Comment by lesjaw** [comment]
waiit..speak to soon.. :-) need more testing on the solution..

**Comment by DaveRicho** [comment]
@lesjaw, do you know what fixed the problem?

I am also getting the same problem on Android (but it is working fine on web for me):

`E/Capacitor/Plugin: Something went wrong
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@18.0.0:9)
        at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.handleOnActivityResult(GoogleAuth.java:70)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:770)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:212)
        at android.app.Activity.dispatchActivityResult(Activity.java:7556)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`

**Comment by DaveRicho** [comment]
I think I got mine working - I'm still confused as to what worked by I think it was this (from https://github.com/googlesamples/google-services/issues/360):

> This error might happen if you are not using same project at console.developers.google and console.firebase.google.com. If project is same at both console make sure you have add your SHA1 Key properly. **Get SHA1 from Android studio**.
> 
> Open Android Studio
> Open your Project
> Click on Gradle (From Right Side Panel, you will see Gradle Bar)
> Click on Refresh (Click on Refresh from Gradle Bar, you will see List Gradle scripts of your Project)
> Click on Your Project (Your Project Name form List (root))
> Click on Tasks
> Click on Android
> Double Click on signingReport (You will get SHA1 and MD5 in Run Bar(Sometimes it will be in Gradle Console))

I then went back to https://console.developers.google.com/apis/credentials and added a new "OAuth 2.0 Client ID" for android and pasted the SHA1 that I got from **Android Studio**. It then seemed to work on the android phone I am using for testing.

Not sure about you, but I found this very confusing!

**Comment by andirsun** [comment]
> I think I got mine working - I'm still confused as to what worked by I think it was this (from [googlesamples/google-services#360](https://github.com/googlesamples/google-services/issues/360)):
> 
> > This error might happen if you are not using same project at console.developers.google and console.firebase.google.com. If project is same at both console make sure you have add your SHA1 Key properly. **Get SHA1 from Android studio**.
> > Open Android Studio
> > Open your Project
> > Click on Gradle (From Right Side Panel, you will see Gradle Bar)
> > Click on Refresh (Click on Refresh from Gradle Bar, you will see List Gradle scripts of your Project)
> > Click on Your Project (Your Project Name form List (root))
> > Click on Tasks
> > Click on Android
> > Double Click on signingReport (You will get SHA1 and MD5 in Run Bar(Sometimes it will be in Gradle Console))
> 
> I then went back to https://console.developers.google.com/apis/credentials and added a new "OAuth 2.0 Client ID" for android and pasted the SHA1 that I got from **Android Studio**. It then seemed to work on the android phone I am using for testing.
> 
> Not sure about you, but I found this very confusing!

Yes, It works for me too

**Comment by Darren120** [comment]
hi pls help. Android studio gives error:

It looks like its reading the CLIENT_ID in index.html that is supposed to be for the web and not the CLIENT_ID from string.xml which is for android.

`E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught [object Object]","url":"http://localhost/polyfills-es2015.js","line":3277,"col":29,"errorObject":"{\"error\":\"idpiframe_initialization_failed\",\"details\":\"Not a valid origin for the client: http://localhost has not been whitelisted for client ID ANDROID-9h1d5lrr4dilv6gurfl4elu2qkpbebop.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID.\"}"}}
`

how do i fix this? Android oAuth don't allow me to whitelist anything only web oAuth allows.


its very confusing, i have 3 client id: web, ios, and android. in capcitor.config.json i put the ios, for index.html i put the web, and for string.xml i put android. 

IOS works. web doesn't work. Android doesn't work as well.

pls help what am i doing wrong?

**Comment by Jmiguel14** [comment]
I had the same problem, it was a mess but I was able to resolve it thanks to this comment, so useful: https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/15#issuecomment-515935930
