### ISSUE TITLE
Bug : Ionic + React

### ISSUE THREAD

**Issue by andirsun** [CodetrixStudio/CapacitorGoogleAuth#52]
Hi im getting this error when try to implement your plugin
this is after select the google account to sign in
```
2020-05-22 22:26:53.820 25970-25970/com.timugo.pets E/Capacitor/Plugin: Something went wrong
    com.google.android.gms.common.api.ApiException: 12500: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@18.0.0:9)
        at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.handleOnActivityResult(GoogleAuth.java:70)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:770)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:212)
        at android.app.Activity.dispatchActivityResult(Unknown Source:11)
        at android.app.ActivityThread.deliverResults(Unknown Source:44)
        at android.app.ActivityThread.handleSendResult(Unknown Source:160)
        at android.app.servertransaction.ActivityResultItem.execute(Unknown Source:11)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:99)
        at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:34)
        at android.app.ActivityThread$H.handleMessage(Unknown Source:36)
        at android.os.Handler.dispatchMessage(Unknown Source:21)
        at android.os.Looper.loop(Unknown Source:207)
        at android.app.ActivityThread.main(Unknown Source:107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
2020-05-22 22:26:53.825 25970-25970/com.timugo.pets D/Capacitor: Sending plugin error: {"save":false,"callbackId":"106465218","pluginId":"GoogleAuth","methodName":"signIn","success":false,"error":{"message":"Something went wrong"}}
```

**Comment by andirsun** [comment]
I just Resolve it, for the people who got the same error need to configure your app in the google cloud developer page, in the area of your app Google Auth0 and provide some info. then the app works fine
