### ISSUE TITLE
went i log in with google on my android

### ISSUE THREAD

**Issue by DarrenHazard13** [CodetrixStudio/CapacitorGoogleAuth#94]
message:something went wrong

**Comment by alexander0205** [comment]
Same Error
Error: Something went wrong
    at Object.fromNative (capacitor-runtime.js:229:14)
    at <anonymous>:1:18 {message: 'Something went wrong', stack: 'Error: Something went wrong
    at Object.fro…or-runtime.js:229:14)
    at <anonymous>:1:18'}
message: 'Something went wrong'
stack: 'Error: Something went wrong\n    at Object.fromNative (capacitor-runtime.js:229:14)\n    at <anonymous>:1:18'

**Comment by MYCRYPTOTV** [comment]
Hi @DarrenHazard13 , I got the same error.. Did you find a solution ?

**Comment by alexander0205** [comment]
@RAPHAELSTZ  I found the error, Was about the credentials with google service for auth
