### ISSUE TITLE
Jest tests failing due to - Unexpected token 'export'

### ISSUE THREAD

**Issue by warrendodsworth** [CodetrixStudio/CapacitorGoogleAuth#99]
"jest": "^26.6.3",
"ts-jest": "^26.4.4",
"@types/jest": "^26.0.23",

Angular CLL 11 project with Ionic-Angular 5

FAIL src/app/home/user-report/user-report.service.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/owen/dev/app-linkmate/node_modules/@codetrix-studio/capacitor-google-auth/dist/esm/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './web';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import '@codetrix-studio/capacitor-google-auth';
        | ^
      2 | 
      3 | import { Injectable } from '@angular/core';
      4 | import { AngularFireAnalytics } from '@angular/fire/analytics';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/app/core/services/auth.service.ts:1:1)

**Comment by villesau** [comment]
I believe this is essentially the same problem: https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/126
